

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.sql.ResultSet;
import java.text.ParseException;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class InsertUpdateDeleteMovie extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddMovie
     */
    public InsertUpdateDeleteMovie() {
        initComponents();
        JTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1_movie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2_delete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1_opis = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDateChooser1_datefrom = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3_update = new javax.swing.JButton();
        Id_text = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        vrijeme = new javax.swing.JComboBox<>();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jTree1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikone/icons8_3d_glasses_100px.png"))); // NOI18N
        jLabel1.setText("Filmovi");

        jLabel2.setText("Ime filma");

        jTextField1_movie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_movieActionPerformed(evt);
            }
        });

        jLabel3.setText("Dvorana");

        jButton1.setText("Spremi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2_delete.setText("Obriši");
        jButton2_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_deleteActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikone/icons8_delete_24px.png"))); // NOI18N

        jLabel5.setText("Od datuma");

        jLabel6.setText("Vrijeme");

        jLabel7.setText("Opis");

        jTextField1_opis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_opisActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dvorana 1", "Dvorana 2", "Dvorana 3", "Dvorana 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Naziv", "opis", "Dvorana", "Od datuma", "Vrijeme"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(255, 51, 51));
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        jButton3_update.setText("Ažuriraj");
        jButton3_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_updateActionPerformed(evt);
            }
        });

        Id_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_textActionPerformed(evt);
            }
        });

        jLabel8.setText("Id");

        vrijeme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18:00", "21:00", "23:00" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jDateChooser1_datefrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1_movie, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(jTextField1_opis)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vrijeme, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton3_update)
                                .addGap(54, 54, 54)
                                .addComponent(jButton2_delete)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Id_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1_movie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField1_opis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jDateChooser1_datefrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(vrijeme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2_delete)
                            .addComponent(jButton3_update)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_movieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_movieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_movieActionPerformed

    private void jButton2_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_deleteActionPerformed
     
        int id = Integer.valueOf(Id_text.getText());
       String movie = jTextField1_movie.getText();
       String opis= jTextField1_opis.getText();
        String value=jComboBox1.getSelectedItem().toString();
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String fdate= dateformat.format(jDateChooser1_datefrom.getDate());
        //String tdate= dateformat.format(jDateChooser2_dateTo.getDate());
         String time=vrijeme.getSelectedItem().toString();
        
        Movie2 mov =new Movie2();
        mov.updateDeleteMovie('d', id, movie, opis, fdate, time);
        
    }//GEN-LAST:event_jButton2_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PreparedStatement Ps;
       
        String movie = jTextField1_movie.getText();
        String opis= jTextField1_opis.getText();
        String value=jComboBox1.getSelectedItem().toString();
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String fdate= dateformat.format(jDateChooser1_datefrom.getDate());
      //  String tdate= dateformat.format(jDateChooser2_dateTo.getDate());
        String time=vrijeme.getSelectedItem().toString();
        
        
        String query="INSERT INTO `movies`(`title`, `description`, `Halls`, `from date`, `to date`) VALUES (?,?,?,?,?)";
        
        
        try {
            Ps = MyConnection.getConnection().prepareStatement(query);
            
            Ps.setString(1, movie);
            Ps.setString(2, opis);
            Ps.setString(3, value);
            Ps.setString(4, fdate);
            Ps.setString(5, time);
            
            if (Ps.executeUpdate()>0){
            
                JOptionPane.showMessageDialog(null, "Uspješno ste dodali film!");
            } 
        } catch (SQLException ex) {
            Logger.getLogger(InsertUpdateDeleteMovie.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

   public ArrayList<Movies1> getmoviesList(){
     
        ArrayList<Movies1> moviesList=new ArrayList<Movies1>();
        
        String query="SELECT * FROM `movies`";
        Statement st;
        ResultSet rs;
        
        try {
            st=MyConnection.getConnection().createStatement();
            rs=st.executeQuery(query);
            
            Movies1 movie;
            
            while(rs.next()){
                movie=new Movies1(rs.getInt("id"),rs.getString("title"),rs.getString("description"),rs.getString("Halls"),rs.getString("from date"),rs.getString("time"));
                moviesList.add(movie);
            }
        } catch (SQLException ex) {
            Logger.getLogger(InsertUpdateDeleteMovie.class.getName()).log(Level.SEVERE, null, ex);
        } 
        return moviesList;
    } 
   
   public void JTable(){
      
     
        ArrayList<Movies1> List=getmoviesList();
        DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
        int indexs[]=jTable1.getSelectedRows();
        Object [] row =new Object[6];
        
        for(int i=0; i<List.size();i++){
            row[0] = List.get(i).getId();
            row[1] = List.get(i).getMovie();
            row[2] = List.get(i).getdescription();
            row[3] = List.get(i).getHall();
            row[4] = List.get(i).getFdate();
            row[5] = List.get(i).getTime();
            
            model.addRow(row);
           
        }
        
       
   }
   public void executeQuery(String query){
       PreparedStatement Ps;
       Statement st;
        try {
            Ps =  MyConnection.getConnection().prepareStatement(query);
            
            if(Ps.executeUpdate(query) == 1){
                 DefaultTableModel model= (DefaultTableModel)jTable1.getModel();
                 model.setRowCount(0);
                 JOptionPane.showMessageDialog(null, "Uspješno!");
            }
          
        } catch (SQLException ex) {
            Logger.getLogger(InsertUpdateDeleteMovie.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
   
    private void jTextField1_opisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_opisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_opisActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int i =jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        Id_text.setText(model.getValueAt(i, 0).toString());
        jTextField1_movie.setText(model.getValueAt(i,1).toString());
        jTextField1_opis.setText(model.getValueAt(i,2).toString());
        jComboBox1.setActionCommand(model.getValueAt(i, 3).toString());
       SimpleDateFormat fromdate,todate;
      
        try {
            Object datefrom= new SimpleDateFormat("yyyy-MM-dd").parseObject(model.getValueAt(i, 4).toString());
            jDateChooser1_datefrom.setDate((java.util.Date) datefrom);
            Object dateto= new SimpleDateFormat("yyyy-MM-dd").parseObject(model.getValueAt(i, 5).toString());
           // jDateChooser2_dateTo.setDate((java.util.Date) dateto);
          
        } catch (ParseException ex) {
            
            Logger.getLogger(InsertUpdateDeleteMovie.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //jDateChooser1_datefrom.setDateFormatString(model.getValueAt(i, 4).toString());
        //jDateChooser2_dateTo.setDateFormatString(model.getValueAt(i, 5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_updateActionPerformed
        // TODO add your handling code here:
       
       int id = Integer.valueOf(Id_text.getText());
       String movie = jTextField1_movie.getText();
       String opis= jTextField1_opis.getText();
       String value=jComboBox1.getSelectedItem().toString();
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String fdate= dateformat.format(jDateChooser1_datefrom.getDate());
       // String tdate= dateformat.format(jDateChooser2_dateTo.getDate());
        String time=vrijeme.getSelectedItem().toString();
        
        Movie2 mov =new Movie2();
        mov.updateDeleteMovie('u', id, movie, opis, fdate, time);
     /* String query="UPDATE `movies` SET `title`="+jTextField1_movie.getText()+" ,`description`="+jTextField1_opis.getText()+",`from date`="+jDateChooser1_datefrom.getDate()+",`to date`="+jDateChooser2_dateTo.getDate()+" WHERE `id`="+Id_text.getText();
        executeQuery(query);*/
        
        
    }//GEN-LAST:event_jButton3_updateActionPerformed

    private void Id_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_textActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public static void main(String args[]) {
      
        
  java.awt.EventQueue.invokeLater(() -> {
            new InsertUpdateDeleteMovie().setVisible(true);
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2_delete;
    private javax.swing.JButton jButton3_update;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1_datefrom;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1_movie;
    private javax.swing.JTextField jTextField1_opis;
    private javax.swing.JTree jTree1;
    private javax.swing.JComboBox<String> vrijeme;
    // End of variables declaration//GEN-END:variables
}
