
import java.awt.Color;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class SeatReservation extends javax.swing.JFrame {

               

    public SeatReservation() {
        initComponents();
           
    }
    PreparedStatement ps ;
    PreparedStatement ps1 ;
     PreparedStatement ps2 ;
     PreparedStatement ps3 ;
    Connection con;
    ResultSet rs;
    
 
    
    public void Load(){
        
         SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
            String Datum= dateformat.format(datum.getDate());
            String query="SELECT seat.hall,seat.seat,seat.status,seat.date,reservation.user,reservation.movie from seat Left JOIN reservation ON seat.hall=reservation.hall AND seat.seat=reservation.seats AND seat.date=reservation.date where seat.date=?";
            
        try {
            // ps = con.prepareStatement("SELECT seat.hall,seat.seat,seat.status,seat.date,reservation.user,reservation.movie from seat Left JOIN reservation ON seat.hall=reservation.hall AND seat.seat=reservation.seat AND seat.date=reservation.date where seat.date=?");
            ps = MyConnection.getConnection().prepareStatement(query);
             ps.setString(1, Datum);
            rs=ps.executeQuery();
            
            ResultSetMetaData rsd=rs.getMetaData();
            int c;
            c=rsd.getColumnCount();
            
            DefaultTableModel d= (DefaultTableModel)jTable1.getModel();
            
            d.setRowCount(0);
            
            while(rs.next()){
                Vector v2=new Vector();
                
                for(int i=1;i<=c;i++){
                    v2.add(rs.getString("hall"));
                     v2.add(rs.getString("seat"));
                      v2.add(rs.getString("status"));
                       v2.add(rs.getString("user"));
                       v2.add(rs.getString("movie"));
                       v2.add(rs.getString("date"));
                
                }
                d.addRow(v2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(SeatReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        datum = new com.toedter.calendar.JDateChooser();
        Prikaz = new javax.swing.JButton();
        sjedalo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        korisnik = new javax.swing.JTextField();
        seat1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        date = new javax.swing.JTextField();
        Spremi = new javax.swing.JButton();
        Ažuriraj = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REZERVACIJE");

        Prikaz.setText("Prikaz");
        Prikaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrikazActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(423, 423, 423)
                .addComponent(jLabel4)
                .addGap(215, 215, 215)
                .addComponent(datum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Prikaz)
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Prikaz)
                    .addComponent(datum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32))
        );

        sjedalo.setBackground(new java.awt.Color(53, 53, 53));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Korisnik");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sjedalo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Datum");

        korisnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                korisnikActionPerformed(evt);
            }
        });

        seat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dvorana", "Sjedalo", "Status", "Korisnik", "Film", "Datum"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Spremi.setText("Spremi");
        Spremi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpremiActionPerformed(evt);
            }
        });

        Ažuriraj.setText("Oslobodi sjedalo");
        Ažuriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AžurirajActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Film");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Film1", "Film2", "Film3", "Film4", "Film5", "-" }));

        jButton1.setText("Obriši rezervaciju");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sjedaloLayout = new javax.swing.GroupLayout(sjedalo);
        sjedalo.setLayout(sjedaloLayout);
        sjedaloLayout.setHorizontalGroup(
            sjedaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sjedaloLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(sjedaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sjedaloLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Spremi)
                        .addGap(65, 65, 65)
                        .addComponent(Ažuriraj))
                    .addGroup(sjedaloLayout.createSequentialGroup()
                        .addGroup(sjedaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(106, 106, 106)
                        .addGroup(sjedaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(seat1)
                            .addComponent(korisnik)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        sjedaloLayout.setVerticalGroup(
            sjedaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sjedaloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sjedaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sjedaloLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(sjedaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(korisnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(sjedaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(sjedaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(seat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(sjedaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(sjedaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Spremi)
                            .addComponent(Ažuriraj)
                            .addComponent(jButton1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sjedalo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sjedalo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrikazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrikazActionPerformed
      
        
    Load();
           
            
     
    }//GEN-LAST:event_PrikazActionPerformed

    private void korisnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_korisnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_korisnikActionPerformed

    private void seat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel d1= (DefaultTableModel)jTable1.getModel();
        int selected =jTable1.getSelectedRow();
        
        String status=d1.getValueAt(selected,2).toString();
        
        if(!status.equals("Rezervirano")){
            String seat=d1.getValueAt(selected,1).toString();
            String date1=d1.getValueAt(selected,5).toString();
            seat1.setText(seat);
            date.setText(date1);
        }
        else{
            JOptionPane.showMessageDialog(this, "Karta je rezervirana");
        }
      
    }//GEN-LAST:event_jTable1MouseClicked

    private void SpremiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpremiActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d1= (DefaultTableModel)jTable1.getModel();
        int selected =jTable1.getSelectedRow();
        
        String hall=d1.getValueAt(selected,0).toString();
        
        String user=korisnik.getText();
         String movie=jComboBox1.getSelectedItem().toString();
          String seat=seat1.getText();
          String date2=date.getText();
            
           String query="INSERT INTO `reservation`( `hall`, `seats`, `user`, `movie`, `date`) VALUES (?,?,?,?,?)";
           String query1="UPDATE seat set status=? where seat=?";
           
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
             ps.setString(1,hall);
             ps.setString(2, seat);
              ps.setString(3,user);
             ps.setString(4, movie);
              ps.setString(5,date2);
           ps.executeUpdate();
           
           ps1=MyConnection.getConnection().prepareStatement(query1);
           ps1.setString(1, "Rezervirano");
           ps1.setString(2, seat);
           ps1.executeUpdate();
          
           
           JOptionPane.showMessageDialog(this, "Rezervirano");
           Load();  
        } catch (SQLException ex) {
            Logger.getLogger(SeatReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
            
             
    }//GEN-LAST:event_SpremiActionPerformed

    private void AžurirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AžurirajActionPerformed
      
           DefaultTableModel d1= (DefaultTableModel)jTable1.getModel();
        int selected =jTable1.getSelectedRow();
        
        String hall=d1.getValueAt(selected,0).toString();
        
        String user=korisnik.getText();
         String movie=jComboBox1.getSelectedItem().toString();
          String seat=seat1.getText();
          String date2=date.getText();
            
           String query="INSERT INTO `reservation`( `hall`, `seats`, `user`, `movie`, `date`) VALUES (?,?,?,?,?)";
           String query1="UPDATE seat set status=? where seat=?";
           
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
             ps.setString(1,hall);
             ps.setString(2, seat);
              ps.setString(3,user);
             ps.setString(4, movie);
              ps.setString(5,date2);
           ps.executeUpdate();
           
           ps1=MyConnection.getConnection().prepareStatement(query1);
           ps1.setString(1, "Slobodno");
           ps1.setString(2, seat);
           ps1.executeUpdate();
          
           
           JOptionPane.showMessageDialog(this, "Sjedalo slobodno,potrebno još odabrati gumb obriši rezervaciju!");
           Load();  
        } catch (SQLException ex) {
            Logger.getLogger(SeatReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_AžurirajActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        DefaultTableModel d1= (DefaultTableModel)jTable1.getModel();
       int selected =jTable1.getSelectedRow();
        
        String hall=d1.getValueAt(selected,0).toString();
        
        String user=korisnik.getText();
         String movie=jComboBox1.getSelectedItem().toString();
          String seat=seat1.getText();
          String date2=date.getText();
         
       //  int id = Integer.valueOf(Id_text.getText());
      // String movie = jTextField1_movie.getText();
      // String opis= jTextField1_opis.getText();
        //String value=jComboBox1.getSelectedItem().toString();
       // SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
       // String fdate= dateformat.format(jDateChooser1_datefrom.getDate());
       // String tdate= dateformat.format(jDateChooser2_dateTo.getDate());
        
        Booking mov =new Booking();
        mov.updateDeleteRes('d', movie, seat, user, date2);
          
          
    }//GEN-LAST:event_jButton1ActionPerformed
    /*public void seat(){
       String seat;
       if(seat.)
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeatReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeatReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeatReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeatReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeatReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ažuriraj;
    private javax.swing.JButton Prikaz;
    private javax.swing.JButton Spremi;
    private javax.swing.JTextField date;
    private com.toedter.calendar.JDateChooser datum;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField korisnik;
    private javax.swing.JTextField seat1;
    private javax.swing.JPanel sjedalo;
    // End of variables declaration//GEN-END:variables
}
